# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - uses: actions/checkout@v4
    - name: Set up Python 3.10 Check out the code from repository
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
     
    # install dependencies    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

   # Run tests
    - name: Run tests
      run: pytest
